<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationTitle>PCue</ApplicationTitle>
    <RootNamespace>PCue</RootNamespace>
    <AssemblyName>PCue</AssemblyName>
    <ApplicationIcon>Assets\Images\favicon.ico</ApplicationIcon>
    <StartupObject>PCue.Program</StartupObject>
    <VlcWindowsX64Enabled>true</VlcWindowsX64Enabled>
    <VlcWindowsX86Enabled>false</VlcWindowsX86Enabled>
    <VlcWindowsArm64Enabled>false</VlcWindowsArm64Enabled>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.1" />
    <PackageReference Include="Velopack" Version="1.2.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.24" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\*.ttf" />
    <Resource Include="Assets\Images\Logo_B.png" />
    <Resource Include="Assets\Images\favicon.ico" />
  </ItemGroup>

</Project>
